package ru.dima.util;

import java.util.List;
import java.util.Random;

public class Words {
    private static final List<String> badWords = List.of(
            "козья морда",
            "душной козел",
            "осёл",
            "баран",
            "боров",
            "пес",
            "та ещё жучка",
            "кобыла",
            "сивый мерин",
            "мартышка",
            "свинья",
            "быдло",
            "давить",
            "хорёк ",
            "змея",
            "волки позорные",
            "корова",
            "напыщенный индюк",
            "безмозглая курица",
            "гусыня",
            "павлин",
            "ворона ловить",
            "сыч",
            "сушеная вобла",
            "каракатица",
            "назойливая муха",
            "вошь на гребешке",
            "гнида",
            "глиста ходячая",
            "жук навозный",
            "приставучий репей",
            "лопух",
            "осиновый лист, заячий хвост",
            "белены объелся",
            "хуже горькой редьки",
            "дать в репу",
            "липовый диплом",
            "разделать под орех",
            "поганка",
            "шут гороховый",
            "дерево",
            "клубничка",
            "банный лист",
            "лох,лохушка",
            "дубина стоеросовая",
            "бестия",
            "грубиян",
            "урка",
            "хабалка",
            "паскуда",
            "шваль,",
            "ворюга",
            "дурак",
            "шаромыга",
            "погань",
            "вонючка",
            "пропойца",
            "стерва",
            "тварь",
            "позорный",
            "дерьмо",
            "лапотник",
            "сволочь",
            "мразь",
            "потаскуха",
            "скряга",
            "дрянь",
            "шпана",
            "шкура",
            "шибздик",
            "шалава",
            "шлюха",
            "шантрапа",
            "шушера",
            "ханыга",
            "гнусь",
            "подлец",
            "брехун",
            "балбес",
            "обалдуй",
            "халявщик",
            "недотепа",
            "тупица",
            "мозгляк",
            "дегенерат",
            "трепло",
            "чучело",
            "пердун",
            "филькина грамота",
            "дистрофик",
            "желчный",
            "шизик",
            "геморрой",
            "язва",
            "вася бардуль",
            "стеллерова газель",
            "кощей",
            "кикимора",
            "карга",
            "леший",
            "урод",
            "харя",
            "морда",
            "мордоворот",
            "рыло",
            "образина"
    );

    private final static List<String> gachiStikersFileId = List.of(
            "CAACAgIAAxkBAAIEh2TbrSRCOQkfXt9UGrl-iYxDIaJnAAJvFgACDakBSPZk3Q3AkxAgMAQ",
            "CAACAgIAAxkBAAIEiGTbrif4sRZlDjA6v8j_XllF1AfaAAI1EgACVtYJSFXCJCqqP-p-MAQ",
            "CAACAgIAAxkBAAIEiWTbrikRXn51P5kEjo4B4C2QyfljAAJ3EgACspshSCLLK1mP0FD4MAQ",
            "CAACAgIAAxkBAAIEimTbrio1x79RCjkJMp_cosoVGXA3AALMGgACTTiAS903g7YkPobmMAQ",
            "CAACAgIAAxkBAAIEi2TbrithLBVOslqMW06NTPQmm3LuAAJ9FgACMPYAAUgXnlYRZQ8jSzAE",
            "CAACAgIAAxkBAAIEjGTbriyUIvgK89oglEOX1IOsu_RJAAJSEwACRIsAAUhzsuV6326FHDAE",
            "CAACAgIAAxkBAAIEjWTbri0_-KvLH58u-0Gah383SQG4AAIQFgAC87sBSNadeX0BLbxbMAQ",
            "CAACAgIAAxkBAAIEjmTbri3VtzQY-BnwdiMYeQcBK-WlAAIBFQAC3c4AAUiTbUOfODgj8zAE",
            "CAACAgIAAxkBAAIEj2Tbri5v5n3kztmL4zJFwmIE56XoAALpEgACbT3ASXwyX8cFZ7EVMAQ",
            "CAACAgIAAxkBAAIEkGTbri7br_bhm5mi4zDMcB426cSlAAIOFAACFxIZSJT7y5ztPPbUMAQ",
            "CAACAgIAAxkBAAIEkWTbrjJ049ZbnirEcARh-PDOSzTZAAJGFwAC0-UBSLxDhiKi36sKMAQ",
            "CAACAgIAAxkBAAIEkmTbrjIzwpw4xybJn1UFlXtUIVLIAAJoGQAC7LoAAUhSloxwAAHl0KYwBA",
            "CAACAgIAAxkBAAIEk2TbrjQSEIZUv5MGHxNtwtML7nkJAALFEwACTRcYSK1RLa3S-X-4MAQ",
            "CAACAgIAAxkBAAIElGTbrjTZ2uiCqiRZg98FInC1UGsFAALwEAAC00EJSNUu4izo18OAMAQ",
            "CAACAgIAAxkBAAIElWTbrjXHA8aCQ5yVXGKFRSKIc3GNAAJNEQAC_KMJSLQszbA_5bMCMAQ",
            "CAACAgIAAxkBAAIElmTbrjbQBJJkbEwWaIKPWq1X-Z4_AAKrFAACknQgSLPT2OXpXNVEMAQ",
            "CAACAgIAAxkBAAIEl2TbrjfAM35rArK9Ep0F_a1OGJICAAIEGQAChLUBSJe2EvJOYZtiMAQ",
            "CAACAgIAAxkBAAIEmGTbrjhsGlUEQf-fQi1MJ9jGvKiuAALvFAACnuIAAUhte6laGguDszAE",
            "CAACAgIAAxkBAAIEmWTbrjguYhI7RJHuNOKk2X2ftjLIAAKpFgAC-boBSOdW3ty9OLwQMAQ",
            "CAACAgIAAxkBAAIEmmTbrjnOGxkc8cDlNlRwLKYEoRTCAAKHEgACjikJSG8um2T9m29RMAQ",
            "CAACAgIAAxkBAAIEm2TbrjqB5KcwDaIj7qmXZVnskeaeAAKwFAACEWcgSJiTpaY3FSOkMAQ",
            "CAACAgIAAxkBAAIEnGTbrjtwBp7V8oMZabEFH1IH8YhGAAK9FAAC7UkAAUjR8ic3lKsQRzAE",
            "CAACAgIAAxkBAAIEnWTbrjtb0vSyxQURhkXxx3XwVmWnAAKxFQAC_ecBSHCc7ZD437rMMAQ",
            "CAACAgIAAxkBAAIEnmTbrjx5Dp8_A1h6duRjofzPnAHzAAIzFAACZmQAAUhRHqqiLoBNQjAE",
            "CAACAgIAAxkBAAIEn2TbrjyZg5HD0T2jnk1zrvzITSgxAAIhFQAC_bIISCYPWmPtIug1MAQ",
            "CAACAgIAAxkBAAIEoGTbrj7ZuOp0oZCu1UOHjPWiA-fhAAJJFAACgCghSIfpu_uQsJPLMAQ",
            "CAACAgIAAxkBAAIEoWTbrj6bPBXRNO_Vn2SPAAFRzMpj2gAC8hYAApHkIEjwQR1cAWXXEjAE",
            "CAACAgIAAxkBAAIEomTbrj8hnuN7uhLO7-W5NAK-tbKAAAIqEwACmgEJSBpDH4yjW8keMAQ",
            "CAACAgIAAxkBAAIEo2TbrkDU1mhWNuA_JuO8Knkd_MSnAAIpFgAC0roAAUgylwbdCVQv1TAE",
            "CAACAgIAAxkBAAIEpGTbrkBc_voEjBti0kQ0Pp4bJ2U-AAI8GAAC4HAZSK1u-P1ni8lYMAQ",
            "CAACAgIAAxkBAAIEpWTbrkHCPrr1n-ct1uqMqY5u8Y2wAAKgGAACjDQZSLIxCS1TE9FSMAQ",
            "CAACAgIAAxkBAAIEpmTbrkISWyoUD7_4NkedHx3raWn2AAKFHAACJw-AS3vgw2--J03YMAQ",
            "CAACAgIAAxkBAAIEp2TbrkL2mxQHdKPMcEiVmzK5wMOPAAKXFwAC4QQAAUiERNze3vuohDAE",
            "CAACAgIAAxkBAAIEqGTbrkPO2rg5mBoZEjR8yMEUIRT8AAJjFQACU4chSLwgiZS9bzdhMAQ",
            "CAACAgIAAxkBAAIEqWTbrkQB9yTGGsVwk5ya29Q_MzluAAIPFQACz2oYSJHOjAona5qPMAQ",
            "CAACAgIAAxkBAAIEqmTbrkW8rRUnxCT-Q1cTegxkdEdQAALIFgACPkshSI765GXaAAGd5DAE",
            "CAACAgIAAxkBAAIEq2Tbrkb0L50l2NSpvSXjMzRQt0QcAAJkFAACNDAhSOIy1Ji9ODjLMAQ",
            "CAACAgIAAxkBAAIErGTbrkf_SzqrdjfHHwTeX0AWP6bYAAJaFAAC6y0YSM0r2BoOlctCMAQ",
            "CAACAgIAAxkBAAIErWTbrkji4oCPvIvnAdPmIHuf8D1jAAJaEwAClrshSHtfKSEr2ks4MAQ",
            "CAACAgIAAxkBAAIErmTbrknnpfnXfMkFCInSFfDfWRKbAAIGEwACUjwhSLSPhDMWiQ7YMAQ",
            "CAACAgIAAxkBAAIEr2TbrksQLWHOy8fpBZEErrqtxksGAAMWAAIIFBhIzo5MhRinClkwBA",
            "CAACAgIAAxkBAAIEsGTbrkyP5SPZ6iPs9EOtDitDrrJeAAIaFwACgIEgSDIWshrnNmbKMAQ",
            "CAACAgIAAxkBAAIEsWTbrkwQldxLWK6ZzP7OuqCuKd2LAAIZFQACAYsYSIFK1aiOw-ttMAQ",
            "CAACAgIAAxkBAAIEsmTbrk0D4TAKL4oKz45iG6TsQUVNAAKuFAACwrkYSP7Noft9GfX7MAQ",
            "CAACAgIAAxkBAAIEs2Tbrk46tSTgE6pt7lruZb5pf5D3AAIYEQACCzwhSBjYlPrCpBGeMAQ",
            "CAACAgIAAxkBAAIEtGTbrk-S8ri1-dEyL3vyL4Mq5f0kAAJOFAAC6HkgSBRO61qtDwW5MAQ",
            "CAACAgIAAxkBAAIEtWTbrlCK44dhlZZAiQUICX9mu9q0AALBEgAC3FAgSKheRgZr6FjGMAQ",
            "CAACAgIAAxkBAAIEtmTbrlGgO3Lb9S96ZxUxwFn0XQAByQACDhUAAjsJGEg1Cw_fT2WG2jAE",
            "CAACAgIAAxkBAAIEt2TbrlIhEK9NFqccEyCh2-X3qIXLAAJ1GQACidU4SJY_dNosKzZ8MAQ",
            "CAACAgIAAxkBAAIEuGTbrlL9ugJTYTfjiLTrk8Zcq7dKAAJCFAACvSJRSGuh5-H7sVjEMAQ"
    );
    private static final Random random = new Random();

    public static String randomBadWord() {
        return badWords.get(random.nextInt(badWords.size()));
    }

    public static String randomGachiStikerFileId() {
        return gachiStikersFileId.get(random.nextInt(gachiStikersFileId.size()));
    }
}
